### ISSUE TITLE
Type error for hospital_sn

### ISSUE THREAD

**Issue by t0mst0ne** [g0v/er.mohw#10]
@lanfon72 maybe need to  s/Hosptial_sn/hospital_sn/g , thanks!

0501110514/ndmctsgh.py
0601160016/tp_vgh.py
0936060016/sltung.py
0943030019/tsmh.py
1101020018/cgh.py
1131010011/femh.py
1131100010/mmh-ts.py
1301200010/wanfangh.py
1331040513/shh.py
1434020015/pohai.py

**Comment by lanfon72** [comment]
all changed, double check please.

**Comment by t0mst0ne** [comment]
All ok, please PR , thanks !!
