### ISSUE TITLE
1101100011 & 1131100010 error.

### ISSUE THREAD

**Issue by lanfon72** [g0v/er.mohw#11]
* FAIL 1101100011 0 crawlers/1101100011/er.mmh.tpe.py
* FAIL 1131100010 0 crawlers/1131100010/mmh-ts.py

error log: 
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

seems https need to vertify.

**Comment by lanfon72** [comment]
* 1145010010
* 0937010019
這兩個 typo, hosptial -> hospital

**Comment by lanfon72** [comment]
@t0mst0ne er.mmh.tpe.py (1101100011) 可能要在 ```requests.get``` 之前先加上 ``` requests.packages.urllib3.disable_warnings() ``` ， requests 在 verify=false 會跳 urllib3 的 warning : 
``` /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning) ```
(上面這行會比 json 早輸出，所以 twer.ls 會抓不到 json )

mmh-ts.py (1131100010) 已修正

**Comment by t0mst0ne** [comment]
感謝！
我20 min crontab 也產生這個Mail

lanf0n <notifications@github.com> 於 2015年2月14日 星期六寫道：

> @t0mst0ne <https://github.com/t0mst0ne> er.mmh.tpe.py (1101100011) 可能要在
> requests.get 之前先加上 requests.packages.urllib3.disable_warnings() ，
> requests 在 verify=false 會跳 urllib3 的 warning :
> /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:734:
> InsecureRequestWarning: Unverified HTTPS request is being made. Adding
> certificate verification is strongly advised. See:
> https://urllib3.readthedocs.org/en/latest/security.html
> InsecureRequestWarning)
> (上面這行會比 json 早輸出，所以 twer.ls 會抓不到 json )
>
> mmh-ts.py (1131100010) 已修正
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/g0v/er.mohw/issues/11#issuecomment-74364168>.
>


-- 
Linger too long at high altitudes, and your hearing dulls, and your
eyesight dims.   "Facing your Giants" , Max Lucado

**Comment by t0mst0ne** [comment]
改了
https://gist.github.com/lanfon72/7a43aedc8e8f7f63ca0a
好像還是 "hosptial_sn"

On Sat, Feb 14, 2015 at 3:33 PM, ChenChang Shih <iamtomstone@gmail.com>
wrote:

> 感謝！
> 我20 min crontab 也產生這個Mail
>
> lanf0n <notifications@github.com> 於 2015年2月14日 星期六寫道：
>
> @t0mst0ne <https://github.com/t0mst0ne> er.mmh.tpe.py (1101100011) 可能要在
>> requests.get 之前先加上 requests.packages.urllib3.disable_warnings() ，
>> requests 在 verify=false 會跳 urllib3 的 warning :
>> /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:734:
>> InsecureRequestWarning: Unverified HTTPS request is being made. Adding
>> certificate verification is strongly advised. See:
>> https://urllib3.readthedocs.org/en/latest/security.html
>> InsecureRequestWarning)
>> (上面這行會比 json 早輸出，所以 twer.ls 會抓不到 json )
>>
>> mmh-ts.py (1131100010) 已修正
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/g0v/er.mohw/issues/11#issuecomment-74364168>.
>>
>
>
> --
> Linger too long at high altitudes, and your hearing dulls, and your
> eyesight dims.   "Facing your Giants" , Max Lucado
>



-- 
Linger too long at high altitudes, and your hearing dulls, and your
eyesight dims.   "Facing your Giants" , Max Lucado

**Comment by lanfon72** [comment]
update, thx~~
