### ISSUE TITLE
parse twer.ls output

### ISSUE THREAD

**Issue by lanfon72** [g0v/er.mohw#13]
crawler fail 的話會有 error log " == " 開頭，其他的大部份就是原始 json ouput。

希望可以把 error log output 成一個檔， daily mail to ......
others 另存成 yymmdd.json 做為備份。

**Comment by t0mst0ne** [comment]
所以您要改twer.ls 嗎 ?

On Sat, Feb 14, 2015 at 11:50 AM, lanf0n <notifications@github.com> wrote:

> crawler fail 的話會有 error log " == " 開頭，其他的大部份就是原始 json ouput。
>
> 希望可以把 error log output 成一個檔， daily mail to ......
> others 另存成 yymmdd.json 做為備份。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/g0v/er.mohw/issues/13>.
>



-- 
Linger too long at high altitudes, and your hearing dulls, and your
eyesight dims.   "Facing your Giants" , Max Lucado

**Comment by lanfon72** [comment]
目前想用 bash 直接接 ls 吐出來的東西去 parse QQ....(剛好最近在看 linux 管理...
爬下來的 json 另外備份的話就不用擔心 influxdb 的問題(and 格式不相容...etc)

**Comment by t0mst0ne** [comment]
Grafana 可以接了嗎?  如果 Grafana 不能接, influxdb 其實就變雞肋 XD

2015-02-14 12:15 GMT+08:00 lanf0n <notifications@github.com>:

> 目前想用 bash 直接接 ls 吐出來的東西去 parse QQ....(剛好最近在看 linux 管理...
> 爬下來的 json 另外備份的話就不用擔心 influxdb 的問題(and 格式不相容...etc)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/g0v/er.mohw/issues/13#issuecomment-74360818>.
>



-- 
Linger too long at high altitudes, and your hearing dulls, and your
eyesight dims.   "Facing your Giants" , Max Lucado

**Comment by lanfon72** [comment]
剛和村長確認過前端只要改 gh-pages 的 ip 就好....

目前資料出不來確定是 sub series 沒有設好，修正完之後就會顯示這幾天的資料了

**Comment by lanfon72** [comment]
first enhance on 4bd7088b7ef051ee3935824e3751e384e8ca72a1

**Comment by lanfon72** [comment]
commit 4b6c62eb94660acc058e93176b0c8155238deb8a solved it.
