### ISSUE TITLE
奇美醫院更新網頁內容

### ISSUE THREAD

**Issue by t0mst0ne** [g0v/er.mohw#14]
http://www.chimei.org.tw/%E6%80%A5%E8%A8%BA%E5%8D%B3%E6%99%82%E8%A8%8A%E6%81%AF/main.aspx?ihosp=10

原來script parsing 只有一間, 並且欄位有變化...

**Comment by lanfon72** [comment]
hospital SNs:
- 奇美醫療財團法人佳里奇美醫院, 1105050012
- 奇美醫療財團法人奇美醫院台南分院, 1121020014
- 奇美醫療財團法人柳營奇美醫院, 1141090512
- 奇美醫療財團法人奇美醫院, 1141310019
(from http://cornguo.nlplab.tw/temp/hospital/parsed.txt )

晚點來修

**Comment by lanfon72** [comment]
奇美  https://gist.github.com/lanfon72/14f08fc32ad0552e7059
奇美柳營 https://gist.github.com/lanfon72/3a3221b3867121114e92
奇美佳里  https://gist.github.com/lanfon72/f174221a2d6b06479c61

**Comment by lanfon72** [comment]
fix on 219c70
