### ISSUE TITLE
無法運行,能否幫忙看看?

### ISSUE THREAD

**Issue by Charl-A** [g0v/er.mohw#16]
node twer.js twer.csv --influxHost [127.0.0.1] --influxDb [ER] --influxUser [admin] --influxPass [admin] > temp && ./backup.sh

/er.mohw/twer.js:116
         throw "wtf " + dir;
         ^
wtf crawlers/1434020015

**Comment by lanfon72** [comment]
please replace [] to null.
`node twer.js twer.csv --influxHost 127.0.0.1 --influxDb ER --influxUser admin --influxPass admin > temp && ./backup.sh`

**Comment by Charl-A** [comment]
@lanfon72 thank u
