### ISSUE TITLE
希望加入 新竹東元以及大林慈濟醫院

### ISSUE THREAD

**Issue by kiang** [g0v/er.mohw#17]
東元 http://w3.tyh.com.tw/se_n_emergency.html#tabs-1
大林慈濟 http://app.tzuchi.com.tw/tchw/ERInfo_DL/ERInformation.aspx

http://logbot.g0v.tw/channel/g0v.tw/2016-03-01#0

**Comment by lanfon72** [comment]
will do.

**Comment by t0mst0ne** [comment]
我加慈濟

**Comment by t0mst0ne** [comment]
請問 @kiang  大林慈濟 和 東元 醫院代號  分別是 ?

**Comment by lanfon72** [comment]
剛對照了一下，目前應該是多三間:
-  新竹市	國立臺灣大學醫學院附設醫院新竹分院
- 新竹縣	東元綜合醫院
- 嘉義縣	佛教慈濟醫療財團法人大林慈濟醫院

**Comment by kiang** [comment]
大林慈濟: 1240030514 ( http://drugs.olc.tw/points/view/54c8f97b-1378-4af5-b7d5-7437d38a10d1 )
東元綜合: 1533050039 ( http://drugs.olc.tw/points/view/54c8f97b-7c3c-43c2-b20b-7437d38a10d1 )

國立臺灣大學醫學院附設醫院新竹分院: 0412040012 ( http://drugs.olc.tw/points/view/54c8f97b-7e00-40ed-b48d-7437d38a10d1 )

**Comment by t0mst0ne** [comment]
大林慈濟 https://gist.github.com/t0mst0ne/34f78aab87ad2d07e271

**Comment by t0mst0ne** [comment]
twer.csv , hospital_json 改完後, 記得要加
git submodule add https://gist.github.com/t0mst0ne/34f78aab87ad2d07e271 crawlers/1240030514
1

**Comment by lanfon72** [comment]
村長之前的 code 有 submodule add( https://github.com/g0v/er.mohw/blob/master/twer.ls#L58 )，看來是沒有 work?

**Comment by t0mst0ne** [comment]
試了一下, 不會用 node js ls ....只好手動加 XD
